site_name: pheval.talos
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Night Mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Day Mode

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - mkdocs-click

plugins:
  - search
  - autorefs
  - include_dir_to_nav
  - mkdocstrings:
      enable_inventory: true

watch:
  - src

nav:
  - "index.md"


site_url: https://yaseminbridges.github.io/pheval_talos/
repo_url: https://github.com/yaseminbridges/pheval_talos
edit_uri: "edit/docs/docs/"
